In [ ]:
import numpy as np #operações matemátcas
import matplotlib.pyplot as plt #plot de gráficos

import pandas as pd # manipulaçao de arquivos (csv, txt)

from sklearn.model_selection import train_test_split # divisão dos dados em treino e teste
from sklearn.neural_network import MLPClassifier

from sklearn.linear_model import LogisticRegression # modelo de classificacao

from sklearn.metrics import accuracy_score

In [ ]:
# Carregamento do arquivo .csv com os dados do Google Drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Leitura do arquivo .csv com os dados para uma variável local

dataset = pd.read_csv('/content/drive/MyDrive/Arquivos/Aplicações - Redes Neurais/Trabalhos/T2: Classificação/predictive_maintenance.csv')

In [ ]:
# Obtem um resumo dos dados que constituem o dataset

dataset.describe()

UDI  Air temperature [K]  ...  Tool wear [min]        Target
count  10000.00000         10000.000000  ...     10000.000000  10000.000000
mean    5000.50000           300.004930  ...       107.951000      0.033900
std     2886.89568             2.000259  ...        63.654147      0.180981
min        1.00000           295.300000  ...         0.000000      0.000000
25%     2500.75000           298.300000  ...        53.000000      0.000000
50%     5000.50000           300.100000  ...       108.000000      0.000000
75%     7500.25000           301.500000  ...       162.000000      0.000000
max    10000.00000           304.500000  ...       253.000000      1.000000

[8 rows x 7 columns]

In [ ]:
dataset.head(3)

UDI Product ID Type  ...  Tool wear [min]  Target  Failure Type
0    1     M14860    M  ...                0       0    No Failure
1    2     L47181    L  ...                3       0    No Failure
2    3     L47182    L  ...                5       0    No Failure

[3 rows x 10 columns]

In [ ]:
# Carrega uma variável local com os dados de entrada
dados = dataset.iloc[:, 3:8].values

# Carrega uma variável local com a opção binária de saída (0 ou 1 para quebra, 1 quando positivo)
resultado = dataset.iloc[:, 8].values

In [ ]:
dados_train, dados_test, resultado_train, resultado_test = train_test_split(dados, resultado, test_size=0.33)

In [ ]:
# Criação do modelo sequencial para formular a rede

modelo = MLPClassifier(hidden_layer_sizes = (20),
                       activation = 'logistic',
                       max_iter = 20000,
                       solver="lbfgs")

modelo.fit(dados_train, resultado_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=20, max_iter=20000,
              solver='lbfgs')

In [ ]:
acuracia = modelo.score(dados_test, resultado_test)
acuracia

0.9657575757575757

In [ ]:
modelo.score(dados_train, resultado_train)

0.9662686567164179

In [ ]:
resultado_pred = modelo.predict(dados_test)

In [ ]:
dados_test[1]

array([ 301.5,  310.6, 1522. ,   36.6,  202. ])

In [ ]:
resultado_test[11]

0

In [ ]:
probs = modelo.predict_proba(dados_test)

In [ ]:
probs

array([[0.96627351, 0.03372649],
       [0.96627351, 0.03372649],
       [0.96627351, 0.03372649],
       ...,
       [0.96627351, 0.03372649],
       [0.96627351, 0.03372649],
       [0.96627351, 0.03372649]])

In [ ]:
np.argmax(probs, axis = 1)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
modelo.ac